# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowVars <- function(mat_in) {
    .Call('BAMBI_rowVars', PACKAGE = 'BAMBI', mat_in)
}

par_mat_permute <- function(par_mat, perm_lab) {
    .Call('BAMBI_par_mat_permute', PACKAGE = 'BAMBI', par_mat, perm_lab)
}

cID <- function(probs, ncomp, Uv) {
    .Call('BAMBI_cID', PACKAGE = 'BAMBI', probs, ncomp, Uv)
}

const_univm <- function(k) {
    .Call('BAMBI_const_univm', PACKAGE = 'BAMBI', k)
}

log_const_univm_all <- function(par_mat) {
    .Call('BAMBI_log_const_univm_all', PACKAGE = 'BAMBI', par_mat)
}

ldunivmnum <- function(x, par) {
    .Call('BAMBI_ldunivmnum', PACKAGE = 'BAMBI', x, par)
}

dunivm_manyx_onepar <- function(x, k, mu) {
    .Call('BAMBI_dunivm_manyx_onepar', PACKAGE = 'BAMBI', x, k, mu)
}

dunivm_manyx_manypar <- function(x, k, mu) {
    .Call('BAMBI_dunivm_manyx_manypar', PACKAGE = 'BAMBI', x, k, mu)
}

dunivm_onex_manypar <- function(x, k, mu) {
    .Call('BAMBI_dunivm_onex_manypar', PACKAGE = 'BAMBI', x, k, mu)
}

runivm_onepar <- function(n, k, mu) {
    .Call('BAMBI_runivm_onepar', PACKAGE = 'BAMBI', n, k, mu)
}

runivm_manypar <- function(k, mu) {
    .Call('BAMBI_runivm_manypar', PACKAGE = 'BAMBI', k, mu)
}

univmmix <- function(x, par, pi, log_c_von) {
    .Call('BAMBI_univmmix', PACKAGE = 'BAMBI', x, par, pi, log_c_von)
}

univmmix_manyx <- function(x, par, pi, log_c) {
    .Call('BAMBI_univmmix_manyx', PACKAGE = 'BAMBI', x, par, pi, log_c)
}

mem_p_univm <- function(data, par, pi, log_c_von, ncores = 1L) {
    .Call('BAMBI_mem_p_univm', PACKAGE = 'BAMBI', data, par, pi, log_c_von, ncores)
}

llik_univm_full <- function(data, par, pi, log_c, ncores = 1L) {
    .Call('BAMBI_llik_univm_full', PACKAGE = 'BAMBI', data, par, pi, log_c, ncores)
}

grad_univm_all_comp <- function(data, par_mat, pi, ncores = 1L) {
    .Call('BAMBI_grad_univm_all_comp', PACKAGE = 'BAMBI', data, par_mat, pi, ncores)
}

l_const_uniwnorm <- function(k) {
    .Call('BAMBI_l_const_uniwnorm', PACKAGE = 'BAMBI', k)
}

const_uniwnorm <- function(k) {
    .Call('BAMBI_const_uniwnorm', PACKAGE = 'BAMBI', k)
}

log_const_uniwnorm_all <- function(par_mat) {
    .Call('BAMBI_log_const_uniwnorm_all', PACKAGE = 'BAMBI', par_mat)
}

lduniwnormnum <- function(x, par, omega_2pi_1d) {
    .Call('BAMBI_lduniwnormnum', PACKAGE = 'BAMBI', x, par, omega_2pi_1d)
}

duniwnorm_manyx_onepar <- function(x, k, mu, omega_2pi_1d) {
    .Call('BAMBI_duniwnorm_manyx_onepar', PACKAGE = 'BAMBI', x, k, mu, omega_2pi_1d)
}

duniwnorm_manyx_manypar <- function(x, k, mu, omega_2pi_1d) {
    .Call('BAMBI_duniwnorm_manyx_manypar', PACKAGE = 'BAMBI', x, k, mu, omega_2pi_1d)
}

duniwnorm_onex_manypar <- function(x, k, mu, omega_2pi_1d) {
    .Call('BAMBI_duniwnorm_onex_manypar', PACKAGE = 'BAMBI', x, k, mu, omega_2pi_1d)
}

uniwnormmix <- function(x, par, pi, log_c_von, omega_2pi_1d) {
    .Call('BAMBI_uniwnormmix', PACKAGE = 'BAMBI', x, par, pi, log_c_von, omega_2pi_1d)
}

uniwnormmix_manyx <- function(x, par, pi, log_c, omega_2pi_1d) {
    .Call('BAMBI_uniwnormmix_manyx', PACKAGE = 'BAMBI', x, par, pi, log_c, omega_2pi_1d)
}

mem_p_uniwnorm <- function(data, par, pi, log_c_von, omega_2pi_1d, ncores = 1L) {
    .Call('BAMBI_mem_p_uniwnorm', PACKAGE = 'BAMBI', data, par, pi, log_c_von, omega_2pi_1d, ncores)
}

llik_uniwnorm_full <- function(data, par, pi, log_c, omega_2pi_1d, ncores = 1L) {
    .Call('BAMBI_llik_uniwnorm_full', PACKAGE = 'BAMBI', data, par, pi, log_c, omega_2pi_1d, ncores)
}

grad_uniwnorm_all_comp <- function(data, par_mat, pi, omega_2pi_1d, ncores) {
    .Call('BAMBI_grad_uniwnorm_all_comp', PACKAGE = 'BAMBI', data, par_mat, pi, omega_2pi_1d, ncores)
}

BESSI0_C <- function(x) {
    .Call('BAMBI_BESSI0_C', PACKAGE = 'BAMBI', x)
}

const_vmcos_anltc <- function(k1, k2, k3) {
    .Call('BAMBI_const_vmcos_anltc', PACKAGE = 'BAMBI', k1, k2, k3)
}

const_vmcos_mc <- function(k1, k2, k3, uni_rand, ncores = 1L) {
    .Call('BAMBI_const_vmcos_mc', PACKAGE = 'BAMBI', k1, k2, k3, uni_rand, ncores)
}

const_vmcos <- function(k1, k2, k3, uni_rand, ncores = 1L) {
    .Call('BAMBI_const_vmcos', PACKAGE = 'BAMBI', k1, k2, k3, uni_rand, ncores)
}

d_const_vmcos_k1_anltc <- function(k1, k2, k3) {
    .Call('BAMBI_d_const_vmcos_k1_anltc', PACKAGE = 'BAMBI', k1, k2, k3)
}

d_const_vmcos_anltc <- function(k1, k2, k3) {
    .Call('BAMBI_d_const_vmcos_anltc', PACKAGE = 'BAMBI', k1, k2, k3)
}

d_const_vmcos_mc <- function(k1, k2, k3, uni_rand, ncores = 1L) {
    .Call('BAMBI_d_const_vmcos_mc', PACKAGE = 'BAMBI', k1, k2, k3, uni_rand, ncores)
}

d_const_vmcos <- function(par, uni_rand, ncores = 1L) {
    .Call('BAMBI_d_const_vmcos', PACKAGE = 'BAMBI', par, uni_rand, ncores)
}

log_const_vmcos_all <- function(par_mat, uni_rand, ncores = 1L) {
    .Call('BAMBI_log_const_vmcos_all', PACKAGE = 'BAMBI', par_mat, uni_rand, ncores)
}

ldcosnum <- function(x, y, par) {
    .Call('BAMBI_ldcosnum', PACKAGE = 'BAMBI', x, y, par)
}

dcos_onex_manypar <- function(x, k1, k2, k3, mu1, mu2, l_const_all) {
    .Call('BAMBI_dcos_onex_manypar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2, l_const_all)
}

dcos_manyx_onepar <- function(x, k1, k2, k3, mu1, mu2, l_const) {
    .Call('BAMBI_dcos_manyx_onepar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2, l_const)
}

dcos_manyx_manypar <- function(x, k1, k2, k3, mu1, mu2, l_const_all) {
    .Call('BAMBI_dcos_manyx_manypar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2, l_const_all)
}

rcos_onepar <- function(n, k1, k2, k3, mu1, mu2, I_upper_bd) {
    .Call('BAMBI_rcos_onepar', PACKAGE = 'BAMBI', n, k1, k2, k3, mu1, mu2, I_upper_bd)
}

rcos_manypar <- function(k1, k2, k3, mu1, mu2, I_upper_bd) {
    .Call('BAMBI_rcos_manypar', PACKAGE = 'BAMBI', k1, k2, k3, mu1, mu2, I_upper_bd)
}

mem_p_cos <- function(data, par, pi, log_c_von, ncores = 1L) {
    .Call('BAMBI_mem_p_cos', PACKAGE = 'BAMBI', data, par, pi, log_c_von, ncores)
}

llik_vmcos_full <- function(data, par, pi, log_c, ncores = 1L) {
    .Call('BAMBI_llik_vmcos_full', PACKAGE = 'BAMBI', data, par, pi, log_c, ncores)
}

grad_log_vmcos_one_comp_i <- function(x, y, par, c_vmcos, del_const_vmcos) {
    .Call('BAMBI_grad_log_vmcos_one_comp_i', PACKAGE = 'BAMBI', x, y, par, c_vmcos, del_const_vmcos)
}

grad_vmcos_all_comp <- function(data, par_mat, pi, uni_rand, ncores = 1L) {
    .Call('BAMBI_grad_vmcos_all_comp', PACKAGE = 'BAMBI', data, par_mat, pi, uni_rand, ncores)
}

vmcosmix <- function(x, y, par, pi, log_c_von) {
    .Call('BAMBI_vmcosmix', PACKAGE = 'BAMBI', x, y, par, pi, log_c_von)
}

vmcosmix_manyx <- function(x, par, pi, log_c_von) {
    .Call('BAMBI_vmcosmix_manyx', PACKAGE = 'BAMBI', x, par, pi, log_c_von)
}

const_vmsin <- function(k1, k2, lambda) {
    .Call('BAMBI_const_vmsin', PACKAGE = 'BAMBI', k1, k2, lambda)
}

d_const_vmsin_lambda <- function(k1, k2, lambda) {
    .Call('BAMBI_d_const_vmsin_lambda', PACKAGE = 'BAMBI', k1, k2, lambda)
}

d_const_vmsin_k1 <- function(k1, k2, lambda) {
    .Call('BAMBI_d_const_vmsin_k1', PACKAGE = 'BAMBI', k1, k2, lambda)
}

d_const_vmsin_k2 <- function(k1, k2, lambda) {
    .Call('BAMBI_d_const_vmsin_k2', PACKAGE = 'BAMBI', k1, k2, lambda)
}

d_const_vmsin <- function(par) {
    .Call('BAMBI_d_const_vmsin', PACKAGE = 'BAMBI', par)
}

log_const_vmsin_all <- function(par_mat) {
    .Call('BAMBI_log_const_vmsin_all', PACKAGE = 'BAMBI', par_mat)
}

ldsinnum <- function(x, y, par) {
    .Call('BAMBI_ldsinnum', PACKAGE = 'BAMBI', x, y, par)
}

dsin_onex_manypar <- function(x, k1, k2, k3, mu1, mu2) {
    .Call('BAMBI_dsin_onex_manypar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2)
}

dsin_manyx_onepar <- function(x, k1, k2, k3, mu1, mu2) {
    .Call('BAMBI_dsin_manyx_onepar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2)
}

dsin_manyx_manypar <- function(x, k1, k2, k3, mu1, mu2) {
    .Call('BAMBI_dsin_manyx_manypar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2)
}

rsin_onepar <- function(n, k1, k2, k3, mu1, mu2, I_upper_bd) {
    .Call('BAMBI_rsin_onepar', PACKAGE = 'BAMBI', n, k1, k2, k3, mu1, mu2, I_upper_bd)
}

rsin_manypar <- function(k1, k2, k3, mu1, mu2, I_upper_bd) {
    .Call('BAMBI_rsin_manypar', PACKAGE = 'BAMBI', k1, k2, k3, mu1, mu2, I_upper_bd)
}

mem_p_sin <- function(data, par, pi, log_c_von, ncores = 1L) {
    .Call('BAMBI_mem_p_sin', PACKAGE = 'BAMBI', data, par, pi, log_c_von, ncores)
}

llik_vmsin_full <- function(data, par, pi, log_c, ncores = 1L) {
    .Call('BAMBI_llik_vmsin_full', PACKAGE = 'BAMBI', data, par, pi, log_c, ncores)
}

grad_vmsin_all_comp <- function(data, par_mat, pi, ncores = 1L) {
    .Call('BAMBI_grad_vmsin_all_comp', PACKAGE = 'BAMBI', data, par_mat, pi, ncores)
}

vmsinmix <- function(x, y, par, pi, log_c_von) {
    .Call('BAMBI_vmsinmix', PACKAGE = 'BAMBI', x, y, par, pi, log_c_von)
}

vmsinmix_manyx <- function(x, par, pi, log_c_von) {
    .Call('BAMBI_vmsinmix_manyx', PACKAGE = 'BAMBI', x, par, pi, log_c_von)
}

ldwnorm2_num <- function(x, par, omega_2pi) {
    .Call('BAMBI_ldwnorm2_num', PACKAGE = 'BAMBI', x, par, omega_2pi)
}

l_const_wnorm2 <- function(par) {
    .Call('BAMBI_l_const_wnorm2', PACKAGE = 'BAMBI', par)
}

const_wnorm2 <- function(par) {
    .Call('BAMBI_const_wnorm2', PACKAGE = 'BAMBI', par)
}

log_const_wnorm2_all <- function(par_mat) {
    .Call('BAMBI_log_const_wnorm2_all', PACKAGE = 'BAMBI', par_mat)
}

mem_p_wnorm2 <- function(data, par_mat, pi, log_c_wnorm, omega_2pi, ncores = 1L) {
    .Call('BAMBI_mem_p_wnorm2', PACKAGE = 'BAMBI', data, par_mat, pi, log_c_wnorm, omega_2pi, ncores)
}

llik_wnorm2_full <- function(data, par, pi, log_c, omega_2pi, ncores = 1L) {
    .Call('BAMBI_llik_wnorm2_full', PACKAGE = 'BAMBI', data, par, pi, log_c, omega_2pi, ncores)
}

grad_den_wnorm2_one_comp_i_unadj <- function(x, y, par, det_sig_inv, det_sig_inv_sqrt, omega_2pi) {
    .Call('BAMBI_grad_den_wnorm2_one_comp_i_unadj', PACKAGE = 'BAMBI', x, y, par, det_sig_inv, det_sig_inv_sqrt, omega_2pi)
}

grad_wnorm2_all_comp <- function(data, par_mat, pi, omega_2pi, ncores = 1L) {
    .Call('BAMBI_grad_wnorm2_all_comp', PACKAGE = 'BAMBI', data, par_mat, pi, omega_2pi, ncores)
}

wnorm2mix <- function(x, par, pi, log_wnorm_const, omega_2pi) {
    .Call('BAMBI_wnorm2mix', PACKAGE = 'BAMBI', x, par, pi, log_wnorm_const, omega_2pi)
}

wnorm2mix_manyx <- function(x, par, pi, log_c_von, omega_2pi) {
    .Call('BAMBI_wnorm2mix_manyx', PACKAGE = 'BAMBI', x, par, pi, log_c_von, omega_2pi)
}

dwnorm2_onex_manypar <- function(x, k1, k2, k3, mu1, mu2, omega_2pi) {
    .Call('BAMBI_dwnorm2_onex_manypar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2, omega_2pi)
}

dwnorm2_manyx_onepar <- function(x, k1, k2, k3, mu1, mu2, omega_2pi) {
    .Call('BAMBI_dwnorm2_manyx_onepar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2, omega_2pi)
}

dwnorm2_manyx_manypar <- function(x, k1, k2, k3, mu1, mu2, omega_2pi) {
    .Call('BAMBI_dwnorm2_manyx_manypar', PACKAGE = 'BAMBI', x, k1, k2, k3, mu1, mu2, omega_2pi)
}

